use ip instead of route when route is not available

diff --git a/bin/add-route b/bin/add-route
--- a/bin/add-route
+++ b/bin/add-route
@@ -1,10 +1,21 @@
 #!/bin/bash
 
-echo "Adding the following route entry to your local route table to enable direct warden container access. Your sudo password may be required."
-echo "  - net 10.244.0.0/19 via 192.168.50.4"
+ips="10.244.0.0/19"
+gw="192.168.50.4"
+
+echo "Adding the following route entry to your local route table to enable direct container access. Your sudo password may be required."
+echo "  - net $ips via $gw"
+
 if [ `uname` = "Darwin" ]; then
-  sudo route delete -net 10.244.0.0/19 192.168.50.4 > /dev/null 2>&1
-  sudo route add -net 10.244.0.0/19 192.168.50.4
+  sudo route delete -net $ips $gw > /dev/null 2>&1
+  sudo route add -net $ips $gw
 elif [ `uname` = "Linux" ]; then
-  sudo route add -net 10.244.0.0/19 gw 192.168.50.4
+  if type route > /dev/null 2>&1; then
+    sudo route add -net $ips gw $gw
+  elif type ip > /dev/null 2>&1; then
+    sudo ip route add $ips via $gw
+  else
+    echo "ERROR adding route"
+    exit 1
+  fi
 fi
